### ISSUE TITLE
[RFE] UUID comparison

### ISSUE THREAD

**Issue by rsevilla87** [cloud-bulldozer/ingress-perf#1]
Implement an UUID comparison mechanism included in the tool. An initial approach could be:

```shell
$ ingress-perf run --cfg config.yaml --es-server=http://whatever.com:9200 --es-index=ingress-performance --compare-with=<baseline_uuid> --accepted-regression=25
Running test...
...
Indexing results...
...
Checking for regressions higher than 25% with UUID...
error: Detected regression in scenario X.Y.Z. Marking rc as 1
```

We can also include these flags as a configuration parameter.

cc: @jtaleric @morenod @dry923 @smalleni

**Comment by jtaleric** [comment]
thoughts on having this in go-commons instead?

**Comment by rsevilla87** [comment]
> thoughts on having this in go-commons instead?

Yeah, that could a better approach, we'd need to find out a reusable and intuitive interface for this library
