### ISSUE TITLE
[RFE] Add support for ppc64le architecture

### ISSUE THREAD

**Issue by varad-ahirwadkar** [cloud-bulldozer/ingress-perf#67]
**Is your feature request related to a problem? Please describe.**
I am trying to run ingress-perf tests on ppc64le architecture but the ingress-perf utilizes the `wrk` tool. Unfortunately, `wrk` does not support the `ppc64le` architecture. 

**Describe alternatives you've considered**
Another  tool which is similar to `wrk` that can be used for HTTP benchmarking and are compatible with the `ppc64le` architecture.

**Comment by kishen-v** [comment]
Hi team, 
We're considering to adopt https://github.com/tsliwowicz/go-wrk in the tool to replace the lua based wrk tool. This may bring down the complexities associated with building wrk across architectures. Please weigh in your thoughts and opinions. This may be a close fit for the existing `wrk` tool.

Looking forward to working on this issue.

Thanks!

**Comment by krishvoor** [comment]
@varad-ahirwadkar @kishen-v: Thanks for bringing this to the notice.
Can you elaborate more on challenges found with Lua + ppc64le in general?

cc: @smalleni @jtaleric @vishnuchalla @mukrishn

**Comment by krishvoor** [comment]
@rsevilla87: Can you advice as well?

**Comment by rsevilla87** [comment]
As @varad-ahirwadkar, wrk requires LuaJIT to compile, and this dependency doesn't have ppc64le support.

Ingress-perf has support for hloader as driver https://github.com/rsevilla87/hloader (which is a tool I built myself some time ago), which is more sophisticated than go-wrk and has support for a wider range of architectures (including ppc64le), there however some issues to be addressed yet:

- There's no ingress-perf release including hloader yet, it was merged some time ago https://github.com/cloud-bulldozer/ingress-perf/pull/55 but as we haven't needed it I haven't cut a release yet
- The ingress-perf image and build system, quay.io/cloud-bulldozer/ingress-perf:latest doesn't have support for ppc64le

Im preparing a set of patches to address these issue, I'll keep you posted, expect some news from me soon!

**Comment by rsevilla87** [comment]
Hi, I cut a new release https://github.com/cloud-bulldozer/ingress-perf/releases/tag/v0.4.2 with the necessary bits to use ingress-perf with the `hloader` driver in ppc64le and s390x

PTAL

**Comment by rsevilla87** [comment]
Also take into account that `hloader` has support for more options, find them described in the docs https://github.com/cloud-bulldozer/ingress-perf?tab=readme-ov-file#reference and a working example in https://github.com/cloud-bulldozer/ingress-perf/blob/main/examples/hloader.yml

**Comment by rsevilla87** [comment]
> Thanks @krishvoor @rsevilla87, able to use ingress-perf with the `hloader`.

Nice, let me know if you have any issues with the tool
